//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.CMS_SKU = new HashSet<CMS_SKU>();
        }
    
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public string ShortName { get; set; }
        public bool Active { get; set; }
        public string Modifier { get; set; }
        public System.DateTime Modifier_Date { get; set; }
    
        public virtual ICollection<CMS_SKU> CMS_SKU { get; set; }
    }
}
