//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.User_Channel_Relation = new HashSet<User_Channel_Relation>();
            this.CMS_SKU = new HashSet<CMS_SKU>();
        }
    
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public string ShortName { get; set; }
        public bool API { get; set; }
        public bool Export2CSV { get; set; }
        public string Modifier { get; set; }
        public System.DateTime Modify_Date { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<User_Channel_Relation> User_Channel_Relation { get; set; }
        public virtual ICollection<CMS_SKU> CMS_SKU { get; set; }
    }
}
