//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_HMGroup_Relation
    {
        public long RID { get; set; }
        public long ProductID { get; set; }
        public long ChildrenProductID { get; set; }
        public int SellSets { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
    
        public virtual CMS_HMNUM CMS_HMNUM { get; set; }
        public virtual CMS_HMNUM CMS_HMNUM_Children { get; set; }
    }
}
