//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_SKU_Category
    {
        public CMS_SKU_Category()
        {
            this.CMS_SKU = new HashSet<CMS_SKU>();
            this.CMS_SKU_Sub = new HashSet<CMS_SKU>();
        }
    
        public long CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public long ParentID { get; set; }
        public long OrderIndex { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public string CreateBy { get; set; }
    
        public virtual ICollection<CMS_SKU> CMS_SKU { get; set; }
        public virtual ICollection<CMS_SKU> CMS_SKU_Sub { get; set; }
        public virtual CMS_SKU_Category CMS_SKU_Category1 { get; set; }
        public virtual CMS_SKU_Category CMS_SKU_Category_Parent { get; set; }
    }
}
