//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_SKU_Material
    {
        public CMS_SKU_Material()
        {
            this.CMS_SKU = new HashSet<CMS_SKU>();
        }
    
        public long MaterialID { get; set; }
        public string MaterialName { get; set; }
        public string MaterialDesc { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public System.DateTime ModifyOn { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual ICollection<CMS_SKU> CMS_SKU { get; set; }
    }
}
