//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ShipVia
    {
        public int SHIPVIAID { get; set; }
        public int ShipViaTypeID { get; set; }
        public string SHIPVIA { get; set; }
        public string CarrierRouting { get; set; }
        public string CarrierCode { get; set; }
        public string ExpressMethod { get; set; }
        public Nullable<int> ExpressNumLength { get; set; }
        public string ExpressRule { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public bool IsDefaultShipVia { get; set; }
    
        public virtual CMS_ShipViaType CMS_ShipViaType { get; set; }
    }
}
