//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_StockKey
    {
        public CMS_StockKey()
        {
            this.CMS_HMNUM = new HashSet<CMS_HMNUM>();
            this.MediaLibrary = new HashSet<MediaLibrary>();
            this.SKU_HM_Relation = new HashSet<SKU_HM_Relation>();
        }
    
        public long StockKeyID { get; set; }
        public string StockKey { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateOn { get; set; }
        public System.DateTime UdateTime { get; set; }
        public string UpdateOn { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<CMS_HMNUM> CMS_HMNUM { get; set; }
        public virtual ICollection<MediaLibrary> MediaLibrary { get; set; }
        public virtual ICollection<SKU_HM_Relation> SKU_HM_Relation { get; set; }
    }
}
