//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ShipViaType
    {
        public CMS_ShipViaType()
        {
            this.CMS_HMNUM = new HashSet<CMS_HMNUM>();
            this.CMS_ShipVia = new HashSet<CMS_ShipVia>();
            this.CMS_SKU = new HashSet<CMS_SKU>();
        }
    
        public int ShipViaTypeID { get; set; }
        public string ShipViaTypeName { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<CMS_HMNUM> CMS_HMNUM { get; set; }
        public virtual ICollection<CMS_ShipVia> CMS_ShipVia { get; set; }
        public virtual ICollection<CMS_SKU> CMS_SKU { get; set; }
    }
}
