//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_SKU_Costing
    {
        public CMS_SKU_Costing()
        {
            this.CMS_SKU = new HashSet<CMS_SKU>();
        }
    
        public long SKUCostID { get; set; }
        public Nullable<long> HMCostID { get; set; }
        public decimal SalePrice { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public long HisSKUID { get; set; }
        public decimal EstimateFreight { get; set; }
    
        public virtual ICollection<CMS_SKU> CMS_SKU { get; set; }
    }
}
