//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ProductCTN
    {
        public long CTNID { get; set; }
        public long ProductID { get; set; }
        public string HMNUM { get; set; }
        public string CTNTitle { get; set; }
        public Nullable<decimal> CTNLength { get; set; }
        public Nullable<decimal> CTNWidth { get; set; }
        public Nullable<decimal> CTNHeight { get; set; }
        public Nullable<decimal> CTNWeight { get; set; }
        public Nullable<decimal> CTNCube { get; set; }
        public string CTNComment { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual CMS_HMNUM CMS_HMNUM { get; set; }
    }
}
