//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public int TenantId { get; set; }
        public int GroupId { get; set; }
        public int Type { get; set; }
        public string OpenId { get; set; }
        public string Nickname { get; set; }
        public int Sex { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string HeadImgUrl { get; set; }
        public string Privilege { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public double Precision { get; set; }
        public Nullable<System.DateTime> LocationTime { get; set; }
        public Nullable<System.DateTime> SubscribeTime { get; set; }
        public Nullable<System.DateTime> UnsubscribeTime { get; set; }
        public string Name { get; set; }
        public string MobilePhone { get; set; }
        public string Job { get; set; }
        public string IdCard { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Income { get; set; }
        public Nullable<bool> HasMarry { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<bool> FirstCar { get; set; }
        public Nullable<bool> IsLoan { get; set; }
        public Nullable<bool> HasHouse { get; set; }
        public string Spouse { get; set; }
        public string SpouseMobilePhone { get; set; }
        public Nullable<System.Guid> PreEmployeeId { get; set; }
        public string PreEmployeeName { get; set; }
        public Nullable<int> PreCarBrandId { get; set; }
        public string PreCarBrandName { get; set; }
        public Nullable<int> PreCarModelId { get; set; }
        public string PreCarModelName { get; set; }
        public bool PreHasComment { get; set; }
        public Nullable<int> PreOrigin { get; set; }
        public Nullable<int> PreImportant { get; set; }
        public Nullable<int> PreStatus { get; set; }
        public Nullable<System.DateTime> PreTime { get; set; }
        public Nullable<System.Guid> AfterEmployeeId { get; set; }
        public string AfterEmployeeName { get; set; }
        public Nullable<int> AfterCarBrandId { get; set; }
        public string AfterCarBrandName { get; set; }
        public string CarProvince { get; set; }
        public string CarCity { get; set; }
        public string License { get; set; }
        public string FrameNo { get; set; }
        public string EngineNo { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<System.DateTime> MaintainDate { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public string InsuranceTel { get; set; }
        public Nullable<System.DateTime> LicenseDate { get; set; }
        public Nullable<System.DateTime> AfterTime { get; set; }
        public int Grade { get; set; }
        public string No { get; set; }
        public string QRCode { get; set; }
        public int MessageBusiness { get; set; }
        public int Point { get; set; }
        public int Signin { get; set; }
        public string Profile { get; set; }
        public System.Guid AttachmentKey { get; set; }
        public Nullable<System.DateTime> SigninTime { get; set; }
        public Nullable<System.DateTime> LatestReadTime { get; set; }
        public Nullable<System.DateTime> ContactTime { get; set; }
        public Nullable<int> SceneId { get; set; }
        public string SceneTitle { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual CustomerSaleExtend CustomerSaleExtend { get; set; }
        public virtual Group Group { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
