//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSaleExtend
    {
        public int Id { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<int> PreImportant { get; set; }
        public Nullable<int> SaleStatus { get; set; }
        public Nullable<int> PreTime { get; set; }
        public Nullable<int> PreCarBrandId { get; set; }
        public string PreCarBrandName { get; set; }
        public Nullable<int> PreCarModelId { get; set; }
        public string PreCarModelName { get; set; }
        public string PreCarColor { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string CarUse { get; set; }
        public string SignNo { get; set; }
        public Nullable<int> CarPrice { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> BudgetCap { get; set; }
        public Nullable<int> BudgetLimit { get; set; }
        public Nullable<bool> IsFirstCar { get; set; }
        public Nullable<bool> IsTestDrive { get; set; }
        public Nullable<bool> IsReplacement { get; set; }
        public Nullable<bool> IsFirstUpdate { get; set; }
        public Nullable<bool> IsLoan { get; set; }
        public Nullable<bool> IsFirstVisit { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastVisitTime { get; set; }
        public Nullable<System.DateTime> LastTaskTime { get; set; }
        public Nullable<int> DriverTimes { get; set; }
        public Nullable<int> CallMinute { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<int> InvitationCount { get; set; }
        public Nullable<int> ToShopCount { get; set; }
        public Nullable<int> DataProgress { get; set; }
        public string Extend { get; set; }
        public string LastCallUrl { get; set; }
        public string CarCharacter { get; set; }
        public Nullable<int> CallTimes { get; set; }
        public Nullable<int> CarBrandId { get; set; }
        public string Budget { get; set; }
        public Nullable<System.DateTime> InvitationTime { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
