//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSaleInfo
    {
        public int Id { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
