//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeSaleInfo = new HashSet<EmployeeSaleInfo>();
        }
    
        public System.Guid Id { get; set; }
        public int TenantId { get; set; }
        public string TenantName { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Image { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string OpenId { get; set; }
        public bool IsLockout { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> AttendTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<EmployeeSaleInfo> EmployeeSaleInfo { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
