//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export2Excel
    {
        public string SKU { get; set; }
        public string ChannelName { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string MaterialName { get; set; }
        public string ColourName { get; set; }
        public string StatusName { get; set; }
        public int SKU_QTY { get; set; }
        public string UPC { get; set; }
        public Nullable<int> Visibility { get; set; }
        public string ProductDesc { get; set; }
        public string Specifications { get; set; }
        public string Keywords { get; set; }
        public string URL { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<long> SubCategoryID { get; set; }
        public string ParentCategoryName { get; set; }
        public Nullable<long> ParentCategoryID { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal SalePrice { get; set; }
        public decimal EstimateFreight { get; set; }
        public string MLHMNUM { get; set; }
        public string ImgName { get; set; }
        public string FileFormat { get; set; }
        public int Pieces { get; set; }
        public string HMNUM { get; set; }
        public long MasterPack { get; set; }
        public string HMName { get; set; }
        public string StockKey { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<int> StockkeyQTY { get; set; }
        public Nullable<decimal> FirstCost { get; set; }
        public Nullable<decimal> OceanFreight { get; set; }
        public Nullable<decimal> USAHandlingCharge { get; set; }
        public Nullable<decimal> Drayage { get; set; }
        public long SKUID { get; set; }
        public int ChannelID { get; set; }
        public int BrandID { get; set; }
        public int StatusID { get; set; }
        public long SKUCostID { get; set; }
        public long ColourID { get; set; }
        public long MaterialID { get; set; }
        public long CategoryID { get; set; }
        public long ProductID { get; set; }
        public long HMCostID { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual CMS_HMNUM CMS_HMNUM { get; set; }
        public virtual CMS_Ecom_Sync CMS_Ecom_Sync { get; set; }
    }
}
