//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOfUserOperatingDetails
    {
        public long ID { get; set; }
        public string ModelName { get; set; }
        public string ActionName { get; set; }
        public int ActionType { get; set; }
        public Nullable<long> SKUID { get; set; }
        public string SKU { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string ChannelName { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string HMNUM { get; set; }
        public string Descriptions { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
    }
}
