//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaLibrary
    {
        public MediaLibrary()
        {
            this.SKU_Media_Relation = new HashSet<SKU_Media_Relation>();
        }
    
        public long MediaID { get; set; }
        public long ProductID { get; set; }
        public long StockKeyID { get; set; }
        public string HMNUM { get; set; }
        public int SerialNum { get; set; }
        public string ImgName { get; set; }
        public int MediaType { get; set; }
        public string fileFormat { get; set; }
        public string fileSize { get; set; }
        public Nullable<int> fileWidth { get; set; }
        public Nullable<int> fileHeight { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CloudStatusID { get; set; }
        public Nullable<bool> PrimaryImage { get; set; }
    
        public virtual ICollection<SKU_Media_Relation> SKU_Media_Relation { get; set; }
        public virtual MediaCloudStatus MediaCloudStatus { get; set; }
        public virtual CMS_StockKey CMS_StockKey { get; set; }
    }
}
