//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaCloudStatus
    {
        public MediaCloudStatus()
        {
            this.MediaLibrary = new HashSet<MediaLibrary>();
        }
    
        public int CloudStatusId { get; set; }
        public string CloudStatusName { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<MediaLibrary> MediaLibrary { get; set; }
    }
}
