//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Resource
    {
        public Menu_Resource()
        {
            this.Role_Menu_Relation = new HashSet<Role_Menu_Relation>();
        }
    
        public int MR_ID { get; set; }
        public string MenuID { get; set; }
        public string ParentMenuID { get; set; }
        public string MenuName { get; set; }
        public int SortNo { get; set; }
        public string MenuUrl { get; set; }
        public string Icon { get; set; }
        public bool Visible { get; set; }
        public string Memo { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    
        public virtual ICollection<Role_Menu_Relation> Role_Menu_Relation { get; set; }
    }
}
