//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Menu_Relation
    {
        public int ID { get; set; }
        public int MR_ID { get; set; }
        public System.Guid Role_GUID { get; set; }
    
        public virtual Security_Role Security_Role { get; set; }
        public virtual Menu_Resource Menu_Resource { get; set; }
    }
}
