//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Role
    {
        public Security_Role()
        {
            this.User_Role_Relation = new HashSet<User_Role_Relation>();
            this.Role_Menu_Relation = new HashSet<Role_Menu_Relation>();
        }
    
        public System.Guid Role_GUID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Desc { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    
        public virtual ICollection<User_Role_Relation> User_Role_Relation { get; set; }
        public virtual ICollection<Role_Menu_Relation> Role_Menu_Relation { get; set; }
    }
}
