//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU_HM_Relation
    {
        public long SKUID { get; set; }
        public long ProductID { get; set; }
        public long StockKeyID { get; set; }
        public int R_QTY { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual CMS_HMNUM CMS_HMNUM { get; set; }
        public virtual CMS_SKU CMS_SKU { get; set; }
        public virtual CMS_StockKey CMS_StockKey { get; set; }
    }
}
