//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUInfo2_V
    {
        public string SKUOrder { get; set; }
        public string SKUName { get; set; }
        public string HMNUM { get; set; }
        public string ProductName { get; set; }
        public string ImageName { get; set; }
        public string ProductPicture { get; set; }
        public int SKU_QTY { get; set; }
        public int StockByPcs { get; set; }
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public int Status { get; set; }
    }
}
