//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUInfo_V
    {
        public string ImageName { get; set; }
        public int LowestInventory { get; set; }
        public long WPID { get; set; }
        public string SKU { get; set; }
        public string ProductName { get; set; }
        public int SKU_QTY { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public int ChannelID { get; set; }
        public int BrandID { get; set; }
        public string ChannelName { get; set; }
        public string BrandName { get; set; }
    }
}
