//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.Customer = new HashSet<Customer>();
            this.Employee = new HashSet<Employee>();
            this.TenantSetting = new HashSet<TenantSetting>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string NamePY { get; set; }
        public string NameShort { get; set; }
        public string Code { get; set; }
        public string Logo { get; set; }
        public string Image { get; set; }
        public string CardImage { get; set; }
        public string CarBrand { get; set; }
        public string CarBrandDisable { get; set; }
        public string CarModelDisable { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string SellTel { get; set; }
        public string ServiceTel { get; set; }
        public string HotlineTel { get; set; }
        public string MaintainTel { get; set; }
        public string SOSTel { get; set; }
        public string ManufacturerTel { get; set; }
        public string Address { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public int Zoom { get; set; }
        public string Region { get; set; }
        public string Contacts { get; set; }
        public string ContactsTel { get; set; }
        public string ContactsEmail { get; set; }
        public string ContactsQQ { get; set; }
        public string Introduce { get; set; }
        public string AccountName { get; set; }
        public int AccountType { get; set; }
        public string QRCode { get; set; }
        public string SourceId { get; set; }
        public string WechatId { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string Token { get; set; }
        public string Url { get; set; }
        public string OAuthDomain { get; set; }
        public int FollowerCount { get; set; }
        public bool IsOpenOnlinePay { get; set; }
        public System.Guid AttachmentKey { get; set; }
        public bool IsEnable { get; set; }
        public int SortIndex { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<TenantSetting> TenantSetting { get; set; }
    }
}
