//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Channel_Relation
    {
        public int ID { get; set; }
        public System.Guid User_Guid { get; set; }
        public int ChannelID { get; set; }
        public string Remark { get; set; }
    
        public virtual CMS_User_Profile_V CMS_User_Profile_V { get; set; }
        public virtual Channel Channel { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
