//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public User_Profile()
        {
            this.User_Channel_Relation = new HashSet<User_Channel_Relation>();
            this.User_Role_Relation = new HashSet<User_Role_Relation>();
        }
    
        public System.Guid User_Guid { get; set; }
        public string User_Account { get; set; }
        public string User_Pwd { get; set; }
        public short UserStatusID { get; set; }
        public Nullable<System.DateTime> Last_Logon { get; set; }
        public Nullable<System.DateTime> Last_Pwd_Chg { get; set; }
        public Nullable<System.DateTime> Pwd_Expire_Date { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Display_Name { get; set; }
        public string Primary_Email { get; set; }
        public string Mobile_Phone { get; set; }
        public string IP_Address { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Locked_By { get; set; }
        public Nullable<System.DateTime> Locked_On { get; set; }
        public Nullable<bool> IsChannelControl { get; set; }
    
        public virtual ICollection<User_Channel_Relation> User_Channel_Relation { get; set; }
        public virtual User_Profile_Ext User_Profile_Ext { get; set; }
        public virtual User_Status User_Status { get; set; }
        public virtual ICollection<User_Role_Relation> User_Role_Relation { get; set; }
    }
}
