//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile_Ext
    {
        public System.Guid UserExt_Guid { get; set; }
        public string Title { get; set; }
        public string Home_Phone { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postal_Code { get; set; }
        public string Country { get; set; }
        public string On_Leave { get; set; }
        public Nullable<System.DateTime> Leave_Start_Date { get; set; }
        public Nullable<System.DateTime> Leave_End_Date { get; set; }
        public Nullable<int> Leave_Seq_No { get; set; }
        public string Second_Emaik { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
    }
}
