//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role_Relation
    {
        public int ID { get; set; }
        public System.Guid User_Guid { get; set; }
        public System.Guid Role_Guid { get; set; }
    
        public virtual Security_Role Security_Role { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
