//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role_Menu_V
    {
        public string User_Account { get; set; }
        public string User_Pwd { get; set; }
        public int MR_ID { get; set; }
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public string ParentMenuID { get; set; }
        public int SortNo { get; set; }
        public string MenuUrl { get; set; }
        public string Icon { get; set; }
    }
}
