//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Status
    {
        public User_Status()
        {
            this.User_Profile = new HashSet<User_Profile>();
        }
    
        public short UserStatusID { get; set; }
        public string UserStatusName { get; set; }
        public string remark { get; set; }
    
        public virtual ICollection<User_Profile> User_Profile { get; set; }
    }
}
