//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPO_HM_Colour_Material_V
    {
        public string HMNUM { get; set; }
        public string ProductName { get; set; }
        public long MaterialID { get; set; }
        public long ColourID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> ParentCategoryID { get; set; }
        public long MasterPack { get; set; }
    }
}
