//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPO_Users_V
    {
        public string UserName { get; set; }
        public string UserPWD { get; set; }
        public string DisplayName { get; set; }
        public long IsDisabled { get; set; }
    }
}
