//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermaisuriCMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPo_NewHM_V
    {
        public string HMNUM { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public long MasterPack { get; set; }
        public decimal GrossWeight { get; set; }
        public string Comment { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> ColourID { get; set; }
        public Nullable<long> MaterialID { get; set; }
        public string StockKey { get; set; }
        public string CTNTitle { get; set; }
        public Nullable<decimal> CTNLength { get; set; }
        public Nullable<decimal> CTNWidth { get; set; }
        public Nullable<decimal> CTNCube { get; set; }
        public Nullable<decimal> CTNHeight { get; set; }
        public string CTNComment { get; set; }
        public string DimTitle { get; set; }
        public Nullable<decimal> DimLength { get; set; }
        public Nullable<decimal> DimWidth { get; set; }
        public Nullable<decimal> DimCube { get; set; }
        public Nullable<decimal> DimHeight { get; set; }
        public string DimComment { get; set; }
    }
}
