//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMSECOM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcomEntities : DbContext
    {
        public EcomEntities()
            : base("name=EcomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Costing> Costing { get; set; }
        public DbSet<Merchant> Merchant { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCartons> ProductCartons { get; set; }
        public DbSet<ProductGroup> ProductGroup { get; set; }
        public DbSet<SKU> SKU { get; set; }
        public DbSet<SKUHistory> SKUHistory { get; set; }
        public DbSet<SKUURL> SKUURL { get; set; }
    }
}
