//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMSECOM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int ID { get; set; }
        public int CUSTNUM { get; set; }
        public string MerchantID { get; set; }
        public string Abbr { get; set; }
        public string CUSTPHONE { get; set; }
        public string PayType { get; set; }
        public string AccNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string OutOfStockKey { get; set; }
        public string PriceKey { get; set; }
        public string Currency { get; set; }
        public string EDINUM { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public string REPNAME { get; set; }
    }
}
