//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMSECOM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string HMNUM { get; set; }
        public Nullable<int> StockID { get; set; }
        public string SKUBest { get; set; }
        public string TAGNUM { get; set; }
        public string Location { get; set; }
        public string BarUPC { get; set; }
        public string ProductPicture { get; set; }
        public string Unit { get; set; }
        public string Colour { get; set; }
        public string InnerMirror { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<short> MasterPack { get; set; }
        public Nullable<int> SellSets { get; set; }
        public Nullable<short> Boxes { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<int> UnitsOnOrder { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public string Comment { get; set; }
        public string DescriptionHM { get; set; }
        public Nullable<System.DateTime> DateOnline { get; set; }
        public string SHIPVIA { get; set; }
        public Nullable<bool> PROMO { get; set; }
        public string FactoryREF { get; set; }
        public Nullable<double> Cube { get; set; }
        public Nullable<bool> IsSET { get; set; }
        public string Vendor { get; set; }
        public string ColourHM { get; set; }
        public Nullable<decimal> CostHM { get; set; }
        public string Store { get; set; }
        public string Department { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public string SKUUSA { get; set; }
        public string Status { get; set; }
        public Nullable<int> LowStock { get; set; }
        public string CommodityDescription { get; set; }
    }
}
