//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMSECOM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public int ProductGropuID { get; set; }
        public string HMNUMParent { get; set; }
        public string HMNUM { get; set; }
        public string Description { get; set; }
        public Nullable<int> SellSets { get; set; }
    }
}
