//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMSECOM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCartons
    {
        public int ProductCartonsID { get; set; }
        public string HMNUM { get; set; }
        public Nullable<int> CartonNumber { get; set; }
        public string Description { get; set; }
        public Nullable<double> CL { get; set; }
        public Nullable<double> CW { get; set; }
        public Nullable<double> CH { get; set; }
        public Nullable<double> PL { get; set; }
        public Nullable<double> PW { get; set; }
        public Nullable<double> PH { get; set; }
        public string INNERMIRROR { get; set; }
        public Nullable<int> WEIGHTOFPRODUCT { get; set; }
        public Nullable<int> WEIGHTOFSHIPMENT { get; set; }
        public Nullable<int> SEATHEIGHT { get; set; }
        public Nullable<int> SEATDIMENSIONSL { get; set; }
        public Nullable<int> SEATDIMENSIONSW { get; set; }
        public Nullable<int> SEATDIMENSIONSH { get; set; }
        public string COMMENTS { get; set; }
        public string SubHMNUM { get; set; }
    }
}
